export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL';

export const WISHLIST_REQUEST = 'WISHLIST_REQUEST';
export const WISHLIST_SUCCESS = 'WISHLIST_SUCCESS';
export const WISHLIST_FAIL = 'WISHLIST_FAIL';

export const WISHLIST_ADD_PRODUCT_REQUEST = 'WISHLIST_ADD_PRODUCT_REQUEST';
export const WISHLIST_ADD_PRODUCT_SUCCESS = 'WISHLIST_ADD_PRODUCT_SUCCESS';
export const WISHLIST_ADD_PRODUCT_FAIL = 'WISHLIST_ADD_PRODUCT_FAIL';

export const WISHLIST_REMOVE_PRODUCT_REQUEST =
  'WISHLIST_REMOVE_PRODUCT_REQUEST';
export const WISHLIST_REMOVE_PRODUCT_SUCCESS =
  'WISHLIST_REMOVE_PRODUCT_SUCCESS';
export const WISHLIST_REMOVE_PRODUCT_FAIL = 'WISHLIST_REMOVE_PRODUCT_FAIL';
